CREATE TABLE `async_batch_task_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(64) NOT NULL DEFAULT '' COMMENT '单号',
  `ext_mark` varchar(64) NOT NULL DEFAULT '' COMMENT '额外标记与orderNo组成唯一索引',
  `spring_handler_class_name` varchar(127) NOT NULL DEFAULT '' COMMENT '执行类名称',
  `request_param` varchar(510) NOT NULL DEFAULT '' COMMENT '参数值',
  `original_request_param` varchar(510) NOT NULL DEFAULT '' COMMENT '参数原值',
  `max_retry_times` tinyint(4) NOT NULL DEFAULT '3' COMMENT '重试次数',
  `fail_times` tinyint(4) NOT NULL DEFAULT '0' COMMENT '失败次数',
  `lowest_interval_time` int(11) NOT NULL DEFAULT '10' COMMENT '上次任务和下次执行之间间隔最短时间(分钟)',
  `next_execute_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次执行时间',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '任务状态',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `gmt_create` bigint(20) NOT NULL DEFAULT '-1' COMMENT '创建时间戳',
  `gmt_update` bigint(20) NOT NULL DEFAULT '-1' COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no_mark_index` (`order_no`,`ext_mark`,`deleted`) USING BTREE,
  KEY `create_time_index` (`create_time`) USING BTREE,
  KEY `gmt_create_index` (`gmt_create`) USING BTREE,
  KEY `gmt_update_index` (`gmt_update`) USING BTREE,
  KEY `execute_time_status_index` (`next_execute_time`,`status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='异步批处理任务'